# -*- coding: utf-8 -*-
"""calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W7JupLCHapHwTeHAGdMtkzKe_c_78unx

Utilize o comando 'input' para receber ao menos 2 números de entrada do usuário;

Converta os valores recebidos pelo usuário para número inteiro (int) ou ponto flutuante (float);

Implemente ao menos 4 operações matemáticas em seu código;

Adicione um laço de repetição ou uma condicional. Por exemplo: você pode permitir que o usuário escolha qual operação realizar ou criar um loop que permita ao usuário realizar várias operações consecutivas;

Utilize o comando 'print' para exibir o resultado da operação matemática.
"""

next_step = None

while next_step != "SAIR":
  num1 = input("Digite o primeiro número (APENAS NÚMEROS INTEIROS): ")
  ## Valida se o primeiro valor é numérico e solicita um novo valor ao usuário caso não seja
  while not num1.isnumeric():
    print("Valor inválido!")
    num1 = input("Digite o primeiro número (APENAS NÚMEROS INTEIROS): ")

  num2 = input("Digite o segundo número (APENAS NÚMEROS INTEIROS): ")
  ## Valida se o segundo valor é numérico e solicita um novo valor ao usuário caso não seja
  while not num2.isnumeric():
    print("Valor inválido!")
    num1 = input("Digite o segundo número (APENAS NÚMEROS INTEIROS): ")

  ## Converte os inputs para floats
  num1_int = int(num1)
  num2_int = int(num2)

  operacao = input("Digite a operação desejada (+, -, /, *):")
  ## Solicita ao usuário inserir uma nova operação caso a originalmente digitada seja inválida
  while operacao != "+" and operacao != "-" and operacao != "/" and operacao != "*":
      print("Operação inválida")
      operacao = input("Digite a operação desejada (+, -, /, *):")

  ##
  if operacao == "+":
    result = num1_int + num2_int
  elif operacao == "-":
    result = num1_int - num2_int
  elif operacao == "/":
      ## Solicita ao usuário inserir uma nova entrada para o segundo número caso o valor original seja zero
      if num2 == "0":
        while not num2.isnumeric() and num2>"0":
          num2 = input("Não é possível dividir por 0, digite outro número (APENAS NÚMEROS INTEIROS): ")
        num2_int = int(num2)
      else:
        result = num1_int / num2_int
  else:
    result = num1_int * num2_int

  ## Imprime o resultado e solicita ao usuário se ele deseja realizar uma nova operação ou sair do programa
  print("O valor final é ", result)
  next_step = input("Deseja fazer outra operação? Digite 'SAIR' para finalizar ou digite qualquer coisa para continuar: ")
  next_step = next_step.upper()